### ISSUE TITLE
Error: req.flash() requires sessions

### ISSUE THREAD

**Issue by anu-priya** [scotch-io/easy-node-authentication#28]
I am getting the below error when open "login" link 

Error: req.flash() requires sessions
    at Error (native)
    at IncomingMessage._flash [as flash] (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\connect-flash\lib\flash.js:60:41)
    at Object.handle (c:\Users\xxx\Desktop\MEAN Stack\shopping\app\routes.js:14:48)
    at next_layer (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\route.js:103:13)
    at Route.dispatch (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\route.js:107:5)
    at c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:195:24
    at Function.proto.process_params (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:251:12)
    at next (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:189:19)
    at next (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:166:38)
    at Layer.handle (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\connect-flash\lib\flash.js:21:5)
    at trim_prefix (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:226:17)
    at c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:198:9
    at Function.proto.process_params (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:251:12)
    at Context.next (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\express\lib\router\index.js:189:19)
    at Context.actions.pass (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\passport\lib\passport\context\http\actions.js:77:8)
    at SessionStrategy.authenticate (c:\Users\xxx\Desktop\MEAN Stack\shopping\node_modules\passport\lib\passport\strategies\session.js:67:10)

Kindly do the needful ASAP

Thanks in Advance

**Comment by iamromuald** [comment]
@anu-priya Couldn't reproduce your bug. It works perfectly here. Try updating your dependancy and give some fresh news ;-)
