### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by CallumBrankin** [scotch-io/easy-node-authentication#35]
After signing in using facebook, this happens:

```
C:\Users\callum.PIXELPIN\Documents\facebook\config\passport.js:106
                    newUser.facebook.email = profile.emails[0].value; // facebook can return multiple emails so we'll take
 the first
                                                           ^

TypeError: Cannot read property '0' of undefined
    at Promise.<anonymous> (C:\Users\callum.PIXELPIN\Documents\facebook\config\passport.js:106:60)
    at Promise.<anonymous> (C:\Users\callum.PIXELPIN\Documents\facebook\node_modules\mpromise\lib\promise.js:177:8)
    at emitOne (events.js:96:13)
    at Promise.emit (events.js:188:7)
    at Promise.emit (C:\Users\callum.PIXELPIN\Documents\facebook\node_modules\mpromise\lib\promise.js:84:38)
    at Promise.fulfill (C:\Users\callum.PIXELPIN\Documents\facebook\node_modules\mpromise\lib\promise.js:97:20)
    at Immediate.cb (C:\Users\callum.PIXELPIN\Documents\facebook\node_modules\mongoose\lib\query.js:1153:30)
    at Immediate.<anonymous> (C:\Users\callum.PIXELPIN\Documents\facebook\node_modules\mquery\lib\utils.js:137:16)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

```

**Comment by jimmiejackson414** [comment]
I'm having this same issue. All I've seen is something about putting brackets around the email in scope as such: `app.get('/auth/facebook', passport.authenticate('facebook', { scope : ['email'] }));`

Still didn't quite work for me though, unfortunately.

**Comment by niograph** [comment]
i got these same error can u pls help me                                                                                                      E:\easy-node-authentication-facebook\easy-node-authentication-facebook>node serv
er.js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
The magic happens on port 8080
GET / 304 21ms
GET /auth/facebook 302 20ms - 400b
E:\easy-node-authentication-facebook\easy-node-authentication-facebook\config\pa
ssport.js:106
                    newUser.facebook.email = profile.emails[0].value; // faceboo
k can return multiple emails so we'll take the first
                                                           ^

TypeError: Cannot read property '0' of undefined
    at Promise.<anonymous> (E:\easy-node-authentication-facebook\easy-node-authe
ntication-facebook\config\passport.js:106:60)
    at Promise.<anonymous> (E:\easy-node-authentication-facebook\easy-node-authe
ntication-facebook\node_modules\mongoose\node_modules\mpromise\lib\promise.js:17
7:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (E:\easy-node-authentication-facebook\easy-node-authenticati
on-facebook\node_modules\mongoose\node_modules\mpromise\lib\promise.js:84:38)
    at Promise.fulfill (E:\easy-node-authentication-facebook\easy-node-authentic
ation-facebook\node_modules\mongoose\node_modules\mpromise\lib\promise.js:97:20)

    at Immediate.cb (E:\easy-node-authentication-facebook\easy-node-authenticati
on-facebook\node_modules\mongoose\lib\query.js:1153:30)
    at Immediate._onImmediate (E:\easy-node-authentication-facebook\easy-node-au
thentication-facebook\node_modules\mongoose\node_modules\mquery\lib\utils.js:137
:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by chrisbrainerd** [comment]
You need to add in `profileFields` in the `FacebookStrategy`, and request `emails`. Like this:
```
...
       clientID        : configAuth.facebookAuth.clientID,
        clientSecret    : configAuth.facebookAuth.clientSecret,
        callbackURL     : configAuth.facebookAuth.callbackURL,
        profileFields   : ['emails'],
        passReqToCallback : true // allows us to pass in the req from our route (lets us check if a user is logged in or not)
...
```

**Comment by Janusz0** [comment]
Firstly, set your profileFields section.
```
'facebookAuth' : {
        'clientID'      : 'your App ID',
        'clientSecret'  : 'your App Secret',
        'callbackURL'   : 'your Callback URL',
        'profileFields'   : ['emails']
    }
```
Now, we need to pull these details wherever we configure our passport code.
```
passport.use(new FacebookStrategy({

        // pull in our app id and secret from our auth.js file
        clientID        : configAuth.facebookAuth.clientID,
        clientSecret    : configAuth.facebookAuth.clientSecret,
        callbackURL     : configAuth.facebookAuth.callbackURL,
        profileFields   : configAuth.facebookAuth.profileFields

    }
```

**Comment by WORMSS** [comment]
@Janusz0 would not supplying the facebookAuth object directly not be the same thing here?

```javascript
passport.use(new FacebookStrategy(configAuth.facebookAuth);
```

**Comment by Janusz0** [comment]
@WORMSS I guess you can do this way too.

**Comment by prdk0** [comment]
HI @Janusz0 , I'm having the same problem, my code is like
```
passport.use(new FacebookStrategy({
    clientID: 'appid',
    clientSecret: 'secret',
    callbackURL: "http://localhost:3000/auth/facebook/callback",
    profileFields: ['id', 'displayName', 'emails']
  },
  function(accessToken, refreshToken, profile, done) {
    User.findOne({facebookId: profile.id}, function(err, user){
        if(err) { return done(err); }
        if(user){
            return done(null, user);
        }else {
            User.findOne({email: profile.emails[0].value}, function(err, user){.......
```
I'm getting `TypeError: Cannot read property '0' of undefined` , what to do?
I'm using 
**"passport": "^0.4.0",
 "passport-facebook": "^2.1.1"**

**Comment by WORMSS** [comment]
I thought it's worth noting. You can sign up to Facebook with JUST a phone number, no email

**Comment by prdk0** [comment]
This https://github.com/jaredhanson/passport-facebook/issues/189#issuecomment-274071211 worked for me.
