### ISSUE TITLE
Authorization code expires in facebook ,what to do

### ISSUE THREAD

**Issue by niograph** [scotch-io/easy-node-authentication#42]
FacebookTokenError: This authorization code has been used. at Strategy.parseErrorResponse (F:\emproject\educationMedia\emWebApp\server\node_modules\passport-facebook\lib\strategy.js:196:12) at Strategy.OAuth2Strategy._createOAuthError (F:\emproject\educationMedia\emWebApp\server\node_modules\passport-facebook\node_modules\passport-oauth2\lib\strategy.js:367:16) at F:\emproject\educationMedia\emWebApp\server\node_modules\passport-facebook\node_modules\passport-oauth2\lib\strategy.js:166:45 at F:\emproject\educationMedia\emWebApp\server\node_modules\passport-facebook\node_modules\passport-oauth2\node_modules\oauth\lib\oauth2.js:177:18 at passBackControl (F:\emproject\educationMedia\emWebApp\server\node_modules\passport-facebook\node_modules\passport-oauth2\node_modules\oauth\lib\oauth2.js:123:9) at IncomingMessage.<anonymous> (F:\emproject\educationMedia\emWebApp\server\node_modules\passport-facebook\node_modules\passport-oauth2\node_modules\oauth\lib\oauth2.js:143:7) at emitNone (events.js:72:20) at IncomingMessage.emit (events.js:166:7) at endReadableNT (_stream_readable.js:905:12) at doNTCallback2 (node.js:441:9)

**Comment by arushi011** [comment]
Were you able to fix this? same is with me
